-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 22:51:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `academia` ;

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
USE `academia` ;

-- -----------------------------------------------------
-- Table `academia`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `endereco` VARCHAR(45) NULL,
  `numeroTelefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dataInscricao` DATE NULL,
  `historicoPagamento` TINYINT NULL,
  `statusAssociacao` TINYINT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Acesso` (
  `IDAcesso` INT NOT NULL AUTO_INCREMENT,
  `dataHoraEntrada` DATETIME NULL,
  `dataHoraSaida` DATETIME NULL,
  `statusPagamento` TINYINT NULL,
  `fk_Aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`IDAcesso`),
  INDEX `fk_Acesso_Aluno1_idx` (`fk_Aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Acesso_Aluno1`
    FOREIGN KEY (`fk_Aluno_matricula`)
    REFERENCES `academia`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Instrutor` (
  `IDInstrutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `numeroTelefone` VARCHAR(45) NULL,
  `especializacao` VARCHAR(45) NULL,
  PRIMARY KEY (`IDInstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Turma` (
  `IDTurma` INT NOT NULL AUTO_INCREMENT,
  `tipoTurma` VARCHAR(45) NULL,
  `horario` INT NULL,
  `qtdAlunos` INT NULL,
  `fk_Instrutor` INT NOT NULL,
  PRIMARY KEY (`IDTurma`),
  INDEX `fk_Turma_Instrutor1_idx` (`fk_Instrutor` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Instrutor1`
    FOREIGN KEY (`fk_Instrutor`)
    REFERENCES `academia`.`Instrutor` (`IDInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Aula` (
  `IDAula` VARCHAR(45) NOT NULL,
  `horario` DATETIME NULL,
  `fk_instrutor` INT NULL,
  `fk_aluno` INT NULL,
  PRIMARY KEY (`IDAula`),
  INDEX `aula_instrutor_idx` (`fk_instrutor` ASC) VISIBLE,
  INDEX `aula_aluno_idx` (`fk_aluno` ASC) VISIBLE,
  CONSTRAINT `aula_instrutor`
    FOREIGN KEY (`fk_instrutor`)
    REFERENCES `academia`.`Instrutor` (`IDInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aula_aluno`
    FOREIGN KEY (`fk_aluno`)
    REFERENCES `academia`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Aluno_has_Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Aluno_has_Turma` (
  `Aluno_matricula` INT NOT NULL,
  `Turma_IDTurma` INT NOT NULL,
  PRIMARY KEY (`Aluno_matricula`, `Turma_IDTurma`),
  INDEX `fk_Aluno_has_Turma_Turma1_idx` (`Turma_IDTurma` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Turma_Aluno1_idx` (`Aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Turma_Aluno1`
    FOREIGN KEY (`Aluno_matricula`)
    REFERENCES `academia`.`Aluno` (`matricula`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_Aluno_has_Turma_Turma1`
    FOREIGN KEY (`Turma_IDTurma`)
    REFERENCES `academia`.`Turma` (`IDTurma`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
